### ISSUE TITLE
About model performance

### ISSUE THREAD

**Issue by WJ1214** [catta202000/CMRNet#12]
Hi, I noticed that the results you provide in this repo are:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/51085092/172124413-9307ae70-b6d1-4008-98fa-828fbc6e335f.png">
While the results you provide in your paper are:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/51085092/172124568-6600a2f6-bcdd-433d-b197-4b88e8a63a90.png">
It seems like there are two different unit of translation error in repo and paper, which one is correct?

**Comment by WJ1214** [comment]
Besides, I'm also confusing about the code in training scipt here:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/51085092/172138221-5b9441cf-6f12-48ae-9ff4-f3d4b3434f72.png">
It seems like used the X coordinate of point cloud to filter the point which is far more than max_depth, why?

**Comment by cattaneod** [comment]
Hi @WJ1214 ,

regarding your first question, you're comparing the results reported in this repo (CMRNet), with the ones reported in the CMRNet++ paper, as they are two different approaches, the results are different.

Regarding your second question, as we project the map (and not a single point cloud) into the virtual image plane, the points could be potentially infinitely far away, that's why we need to set a maximum distance.

**Comment by WJ1214** [comment]
> Hi @WJ1214 ,
> 
> regarding your first question, you're comparing the results reported in this repo (CMRNet), with the ones reported in the CMRNet++ paper, as they are two different approaches, the results are different.
> 
> Regarding your second question, as we project the map (and not a single point cloud) into the virtual image plane, the points could be potentially infinitely far away, that's why we need to set a maximum distance.

Sorry, I confused these two works. Do you have any idea for releasing CMRNet++ code？
